[project]
name = "hand-on-machine-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ChenZhang", email = "340355960@qq.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
hand-on-machine-learning = "hand_on_machine_learning:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
